# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: de1b83ce1af5e2138c448c908aee6e87985382caa068a6fcf0007279b169558e6545f704940052a19f1b6709e86a20c101d1152aafd4608a298c0f4c5ad63e14

test:
  secret_key_base: a10f0d4bd0b40def85ba5a2b83b32d276014d368b5df63f3355ab181ed8b83a973427bb5741a4964281521c6fe04aff23abc18e81291785dcc63f75c164cfaa6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
